#!/bin/bash

echo "Run ./AllClean before running this script, when switching from Linux to Win or vise versa"
export psCXX=x86_64-w64-mingw32-g++
export psCFLAGS=-std=c++0x
export psLFLAGS=" -static -static-libstdc++ -static-libgcc "
export OPT=.exe
export preCC=x86_64-w64-mingw32-
export psHost=Windows
sleep 1

#if ! [ -d thirdparty ]; then
	#if [ -d ../thirdparty ]; then
		#ln -s ../thirdparty ./
	#fi
#fi
#if ! [ -d bin ]; then
	#if [ -d ../bin/ ]; then
		#ln -s ../bin ./
	#fi
#fi

SetedpsDir="$psDir"

myCurrentDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo Running ${BASH_SOURCE[0]} on $myCurrentDIR  \{
if ! [ -n "$psDir" ]; then
	echo " ";
	echo " PoreScale paths are not set"
	echo " please set them (preferably in your ~/.bashrc file) by adding in a new line:"
	echo " Press Cntrl+C to stop ";	echo " ";
	sleep 1
	echo "source $myCurrentDIR/bashrc"
	source $myCurrentDIR/bashrc
fi



if [ -n "$1" ]; then
    dataFiles=$1
else
	dataFiles="$(ls -d */ )"
fi



# needed to compile thirdparty libraries first 
for case in $dataFiles ; do
  if [ -f $case/makefile ]; then 
    echo ;  echo "* cd $case && make:"
	 (cd $case && make)
  fi
done

for case in $dataFiles ; do
  if [ -f $case/Makefile ]; then 
    echo ;  echo "* cd $case && make:"
	 (cd $case && make)
  elif [ -f $case/makefile ]; then echo
  else
    echo "* skipping $case"
  fi
done


echo "Note: run ./AllClean before running this script, when switching from Linux to Win or vise versa"


echo "bin directory: $psBinDir"
if ! [ -n "$SetedpsDir" ]; then
	echo " ";	echo " ";
	echo " variable psDir is not permanently set"
	echo " please set in your ~/.bashrc file by adding new line:"
	echo "source $psDir/bashrc"
	echo " ";
fi

x86_64-w64-mingw32-objdump -p  $psBinDir/pnflow.exe    | grep 'DLL Name:'
